#!groovy

pipeline {
    agent { node 'dev_mesos_v2' }
    tools {
        nodejs "NodeJS 16.x"
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '30', daysToKeepStr: '30'))
        timestamps()
        timeout(time: 30, unit: 'MINUTES')
    }
    stages {
        stage('Test') {
            steps {
                sh """
                    npm install -g npm
                    npm ci --silent

                    cd spigot-tests

                    echo "installing spigot dependencies"
                    npm ci

                    echo "starting tests"
                    npm run test:ci
                """
            }
            post {
                always {
                    junit 'spigot-tests/reports/xunit.xml'
                }
            }
        }
    }
}
